[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "helpers"
version = "0.1"
dependencies = [
        
    ]
readme = "README.md"
requires-python = ">=3.12.3"
[tool.setuptools.packages.find]
where = ["src"]
